---
collections:
- name: vmware.vmware
- name: community.general
- name: containers.podman
- name: community.mysql
- name: kubernetes.core
- name: community.crypto
- name: google.cloud
- name: chocolatey.chocolatey
- name: community.hashi_vault
- name: community.windows
- name: operator_sdk.util
- name: community.docker
- name: ansible.posix
- name: community.digitalocean
- name: community.postgresql
- name: ansible.utils
